### ISSUE TITLE
Single GPU Training problem

### ISSUE THREAD

**Issue by GeoVectorMatrix** [LifeBeyondExpectations/ECCV22-PointMixer#8]
Traceback (most recent call last):
  File "/home/Prjs/ECCV22-PointMixer-main/sem_seg/train_pl.py", line 157, in <module>
    cli_main()
  File "/home/Prjs/ECCV22-PointMixer-main/sem_seg/train_pl.py", line 150, in cli_main
    trainer.fit(model, train_loader, val_loader)
  File "/home/anaconda3/envs/pointmixer/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 738, in fit
    self._call_and_handle_interrupt(
  File "/home/anaconda3/envs/pointmixer/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 683, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/anaconda3/envs/pointmixer/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 773, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/anaconda3/envs/pointmixer/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
.
.
.
.

raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

**Comment by GeoVectorMatrix** [comment]
> Traceback (most recent call last): File "/home/Prjs/ECCV22-PointMixer-main/sem_seg/train_pl.py", line 157, in cli_main() File "/home/Prjs/ECCV22-PointMixer-main/sem_seg/train_pl.py", line 150, in cli_main trainer.fit(model, train_loader, val_loader) File "/home/anaconda3/envs/pointmixer/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 738, in fit self._call_and_handle_interrupt( File "/home/anaconda3/envs/pointmixer/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 683, in _call_and_handle_interrupt return trainer_fn(*args, **kwargs) File "/home/anaconda3/envs/pointmixer/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 773, in _fit_impl self._run(model, ckpt_path=ckpt_path) File "/home/anaconda3/envs/pointmixer/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run self._dispatch() . . . .
> 
> **raise RuntimeError("Default process group has not been initialized, " RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.**

Solved by
    https://github.com/megvii-model/YOLOF/issues/11#issuecomment-805454000

I am not sure whether this is the right solution, but it works

**Comment by LifeBeyondExpectations** [comment]
I did not yet check the full code implementation.
Especially, the current code for semseg utilizes the old version of pytorchlightning, which could be the reason of this issue.

After I check the overall code, then I will close the session. 
Thanks for letting me know the issue.
